### ISSUE TITLE
Search not searching the command field

### ISSUE THREAD

**Issue by evidanary** [tejal29/grepg#4]
https://github.com/tejal29/grepg/blob/master/src/python/grepg/lib/grepg_client.py#L79

Can we search the command field in addition to the description?

**Comment by tejal29** [comment]
Fixed it.
`12:18:06 00:01       [run]
User: tejal29, Topic: Misc, Search-Term: Cmd, Last fetched: 20 second(s) ago
Turn into a link
Cmd + k 


12:18:07 00:02     [jvm]
12:18:07 00:02   [complete]
               SUCCESS
tejals-MacBook-Air:grepg Tejal$ `
